[package]
name = "simple"
type = "contract"
authors = [""]
compiler_version = "0.1"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.8.9", directory="yarn-project/aztec-nr/aztec" }
